spring:
  application:
    name: crossfit-real-world-application
  datasource:
    url: jdbc:postgresql://localhost:5432/crossfit_real_world
    username: crossfit
    password: crossfit
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
